'use client';
import { useEffect, useState, type ReactNode } from 'react';
import { adminFetch, getAdminToken } from '../../lib/browser-api';
import { labelOf } from '../../lib/labels';
import { buildQuery, PaginationControls, type ListMeta } from '../ui/list-pagination';

type Row={id:string;name:string;slug:string;studio:string|null;description:string|null;status:string;availability:string;basePrice:string|null;compareAtPrice:string|null;images?:{id:string;url:string}[];tags?:{id:string;name:string;slug:string}[]};
type Filters={q:string;status:string;availability:string;sortBy:string;sortOrder:string;page:number;pageSize:number};
const defaults:Filters={q:'',status:'',availability:'',sortBy:'createdAt',sortOrder:'desc',page:1,pageSize:20};
const price=(v:string|null)=>!v?'Liên hệ shop':Number.isNaN(Number(v))?v:`${new Intl.NumberFormat('vi-VN').format(Number(v))} ₫`;
const parts=(v:FormDataEntryValue|null,s:string)=>String(v??'').split(s).map(x=>x.trim()).filter(Boolean);

export function CatalogAdminPanel(){
 const [products,setProducts]=useState<Row[]>([]),[filters,setFilters]=useState(defaults),[meta,setMeta]=useState<ListMeta|null>(null),[editingId,setEditingId]=useState<string|null>(null),[message,setMessage]=useState('Đang tải sản phẩm...');
 async function load(next:Filters=filters){if(!getAdminToken()){setMessage('Vui lòng đăng nhập quản trị trước.');return}try{const p=await adminFetch<{data:Row[];meta:ListMeta}>(`/admin/products?${buildQuery(next)}`);setProducts(p.data);setMeta(p.meta);setFilters(next);setMessage(p.data.length?'':'Không có sản phẩm phù hợp.')}catch(e){setMessage(e instanceof Error?e.message:'Không tải được sản phẩm.')}}
 useEffect(()=>{void load(defaults)},[]);
 function filter(d:FormData){void load({q:String(d.get('q')??'').trim(),status:String(d.get('status')??''),availability:String(d.get('availability')??''),sortBy:String(d.get('sortBy')??'createdAt'),sortOrder:String(d.get('sortOrder')??'desc'),page:1,pageSize:Number(d.get('pageSize')??20)})}
 function sort(column:string){void load({...filters,sortBy:column,sortOrder:filters.sortBy===column&&filters.sortOrder==='asc'?'desc':'asc',page:1})}
 async function save(r:Row,d:FormData){setMessage('Đang cập nhật...');try{await adminFetch(`/products/${r.id}`,{method:'PATCH',body:JSON.stringify({name:String(d.get('name')??''),slug:String(d.get('slug')??''),studio:String(d.get('studio')??'')||null,description:String(d.get('description')??'')||null,status:String(d.get('status')??'ACTIVE'),availability:String(d.get('availability')??'PRE_ORDER'),basePrice:String(d.get('basePrice')??''),compareAtPrice:String(d.get('compareAtPrice')??''),tags:parts(d.get('tags'),','),images:parts(d.get('imageUrls'),'\n').map((url,i)=>({url,altText:String(d.get('name')??r.name),sortOrder:i}))})});setEditingId(null);await load();setMessage('Đã cập nhật sản phẩm.')}catch(e){setMessage(e instanceof Error?e.message:'Không cập nhật được sản phẩm.')}}
 async function remove(product:Row){if(!window.confirm(`Xóa vĩnh viễn sản phẩm “${product.name}”?\n\nHình ảnh, biến thể và dữ liệu catalog liên quan sẽ bị xóa và không thể khôi phục. Lịch sử đơn hàng vẫn giữ bản chụp sản phẩm.`))return;setMessage('Đang xóa vĩnh viễn sản phẩm...');try{await adminFetch(`/products/${product.id}`,{method:'DELETE'});await load();setMessage('Đã xóa vĩnh viễn sản phẩm.')}catch(e){setMessage(e instanceof Error?e.message:'Không xóa được sản phẩm.')}}
 const Head=({column,children}:{column:string;children:ReactNode})=><button type="button" className="sort-head" onClick={()=>sort(column)}>{children}<span>{filters.sortBy===column?(filters.sortOrder==='asc'?'↑':'↓'):'↕'}</span></button>;
 return <div className="detail-stack">
  <section className="admin-panel filter-panel"><div className="filter-title"><div><strong>Bộ lọc sản phẩm</strong><span>Tìm kiếm và thu hẹp danh sách nhanh chóng</span></div>{meta&&<small>{meta.total} sản phẩm</small>}</div><form className="admin-form filter-form" action={filter}>
   <label className="search-field"><span>Tìm kiếm</span><div><b>⌕</b><input name="q" defaultValue={filters.q} placeholder="Tên, studio, mô tả..."/></div></label>
   <label><span>Trạng thái</span><select name="status" defaultValue={filters.status}><option value="">Tất cả</option><option value="DRAFT">Bản nháp</option><option value="ACTIVE">Đang bán</option><option value="ARCHIVED">Lưu trữ</option></select></label>
   <label><span>Tình trạng</span><select name="availability" defaultValue={filters.availability}><option value="">Tất cả</option><option value="PRE_ORDER">Đặt trước</option><option value="ORDER">Đặt hàng</option><option value="IN_STOCK">Có sẵn</option><option value="SALE">Giảm giá</option><option value="CONTACT">Liên hệ</option></select></label>
   <label><span>Sắp xếp</span><select name="sortBy" defaultValue={filters.sortBy}><option value="createdAt">Ngày tạo</option><option value="name">Tên</option><option value="price">Giá</option></select></label><label><span>Thứ tự</span><select name="sortOrder" defaultValue={filters.sortOrder}><option value="desc">Giảm dần</option><option value="asc">Tăng dần</option></select></label><label className="page-size"><span>Hiển thị</span><select name="pageSize" defaultValue={filters.pageSize}><option>10</option><option>20</option><option>50</option><option>100</option></select></label><button type="submit">Áp dụng</button>
  </form></section>
  <section className="table-panel catalog-table"><div className="table-row catalog-row table-head"><Head column="name">Sản phẩm</Head><span>Trạng thái</span><span>Tình trạng</span><span>Tag</span><Head column="price">Giá</Head><span>Hành động</span></div>
   {products.map(r=>editingId===r.id?<form className="table-row catalog-edit-row" action={d=>void save(r,d)} key={r.id}><label>Tên<input name="name" defaultValue={r.name} required/></label><label>Slug<input name="slug" defaultValue={r.slug} required/></label><label>Studio<input name="studio" defaultValue={r.studio??''}/></label><label>Trạng thái<select name="status" defaultValue={r.status}><option value="DRAFT">Bản nháp</option><option value="ACTIVE">Đang bán</option><option value="ARCHIVED">Lưu trữ</option></select></label><label>Tình trạng<select name="availability" defaultValue={r.availability}><option value="PRE_ORDER">Đặt trước</option><option value="ORDER">Đặt hàng</option><option value="IN_STOCK">Có sẵn</option><option value="SALE">Giảm giá</option><option value="CONTACT">Liên hệ</option></select></label><label>Giá<input name="basePrice" defaultValue={r.basePrice??''}/></label><label>Giá so sánh<input name="compareAtPrice" defaultValue={r.compareAtPrice??''}/></label><label>Tag<input name="tags" defaultValue={r.tags?.map(t=>t.name).join(', ')??''}/></label><label>URL ảnh<textarea name="imageUrls" defaultValue={r.images?.map(i=>i.url).join('\n')??''}/></label><label className="wide-field">Mô tả<textarea name="description" defaultValue={r.description??''}/></label><div className="row-actions wide-field"><button>Lưu thay đổi</button><button type="button" className="secondary-button" onClick={()=>setEditingId(null)}>Hủy</button></div></form>:
    <div className="table-row catalog-row" key={r.id}><div className="product-cell"><div className="product-thumb" style={r.images?.[0]?{backgroundImage:`url(${r.images[0].url})`}:undefined}>{!r.images?.[0]&&'◇'}</div><strong>{r.name}<small>{r.studio||r.slug}</small></strong></div><span><i className={`status-chip status-${r.status.toLowerCase()}`}>{labelOf(r.status)}</i></span><span><i className="availability-chip">{labelOf(r.availability)}</i></span><span className="tag-list">{r.tags?.length?r.tags.slice(0,2).map(t=><i key={t.id}>{t.name}</i>):<em>Chưa có</em>}</span><strong className="price-cell">{price(r.basePrice)}</strong><span className="action-cell"><details><summary>Hành động <b>⌄</b></summary><div><a href={`/catalog/${encodeURIComponent(r.id)}/edit`}>Xem chi tiết</a><button type="button" onClick={()=>setEditingId(r.id)}>Chỉnh sửa</button><button type="button" className="danger-menu-item" onClick={()=>void remove(r)}>Xóa sản phẩm</button></div></details></span></div>)}{message&&<p className="admin-message table-message">{message}</p>}
  </section><PaginationControls meta={meta} onPageChange={page=>void load({...filters,page})}/>
 </div>
}
