'use client';
import { useState, type ChangeEvent, type DragEvent } from 'react';

const apiUrl=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001/api/v1';
const materials=['Resin tiêu chuẩn','Resin chi tiết cao','Resin chuyên dụng cho mô hình','Cần shop tư vấn'];

export function PrintRequestForm(){
 const [files,setFiles]=useState<File[]>([]),[dragging,setDragging]=useState(false),[submitting,setSubmitting]=useState(false),[message,setMessage]=useState(''),[successId,setSuccessId]=useState('');
 function add(next:File[]){setFiles(current=>[...current,...next.filter(file=>file.type.startsWith('image/'))].slice(0,10))} function select(e:ChangeEvent<HTMLInputElement>){add(Array.from(e.target.files??[]))} function drop(e:DragEvent<HTMLLabelElement>){e.preventDefault();setDragging(false);add(Array.from(e.dataTransfer.files))}
 async function upload(file:File){const intentResponse=await fetch(`${apiUrl}/files/upload-intent`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({originalName:file.name,mimeType:file.type,size:file.size,isPublic:true})});const intent=await intentResponse.json();if(!intentResponse.ok)throw new Error(intent.message||'Không tạo được phiên tải ảnh.');const upload=await fetch(intent.upload.url,{method:intent.upload.method||'PUT',headers:intent.upload.headers,body:file});if(!upload.ok)throw new Error(`Không tải được ${file.name}.`);const confirmedResponse=await fetch(`${apiUrl}/files/${intent.file.id}/confirm`,{method:'PATCH',credentials:'include'});const confirmed=await confirmedResponse.json();if(!confirmedResponse.ok||!confirmed.url)throw new Error('Không xác nhận được ảnh đã tải.');return confirmed.url as string}
 async function submit(data:FormData){if(!files.length){setMessage('Vui lòng thêm ít nhất một hình ảnh tham khảo.');return}setSubmitting(true);setMessage('Đang tải hình ảnh và gửi yêu cầu...');try{const imageUrls=await Promise.all(files.map(upload));const response=await fetch(`${apiUrl}/print-requests`,{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({customerName:String(data.get('customerName')??''),email:String(data.get('email')??''),phone:String(data.get('phone')??''),modelName:String(data.get('modelName')??''),scale:String(data.get('scale')??'')||null,dimensions:String(data.get('dimensions')??'')||null,quantity:Number(data.get('quantity')??1),material:String(data.get('material')??'')||null,color:String(data.get('color')??'')||null,note:String(data.get('note')??'')||null,imageUrls})});const result=await response.json();if(!response.ok)throw new Error(result.message||'Không gửi được yêu cầu.');setSuccessId(result.id);setMessage('Yêu cầu đã được gửi. Shop sẽ liên hệ sau khi kiểm tra hình ảnh.')}catch(error){setMessage(error instanceof Error?error.message:'Không gửi được yêu cầu.')}finally{setSubmitting(false)}}
 if(successId)return <section className="print-request-success"><span>✓</span><h2>Đã nhận yêu cầu của bạn</h2><p>Mã yêu cầu: <strong>{successId}</strong></p><p>Hanbotorder sẽ kiểm tra mẫu và liên hệ để tư vấn kích thước, vật liệu và báo giá.</p><a href="/">Về trang chủ</a></section>;
 return <form className="print-request-form" action={submit}>
  <section className="print-form-section"><div className="print-section-heading"><b>01</b><div><h2>Thông tin liên hệ</h2><p>Shop dùng thông tin này để gửi tư vấn và báo giá.</p></div></div><div className="print-form-grid"><label>Họ và tên<input name="customerName" required/></label><label>Email<input name="email" type="email" required/></label><label>Số điện thoại<input name="phone" required/></label></div></section>
  <section className="print-form-section"><div className="print-section-heading"><b>02</b><div><h2>Thông tin mẫu cần in</h2><p>Càng chi tiết, báo giá ban đầu càng chính xác.</p></div></div><div className="print-form-grid"><label>Tên mẫu<input name="modelName" placeholder="Ví dụ: nhân vật chibi ngồi" required/></label><label>Tỷ lệ / Scale<input name="scale" placeholder="1/6, 1/8, chibi..."/></label><label>Kích thước mong muốn<input name="dimensions" placeholder="Cao 15 cm"/></label><label>Số lượng<input name="quantity" type="number" min="1" max="100" defaultValue="1" required/></label><label>Loại resin<select name="material" defaultValue={materials[0]}>{materials.map(x=><option key={x}>{x}</option>)}</select></label><label>Màu mong muốn<input name="color" placeholder="Xám, trắng, trong suốt..."/></label><label className="wide-field">Mô tả thêm<textarea name="note" rows={6} placeholder="Chi tiết cần giữ, chia part, xử lý support, deadline hoặc yêu cầu hậu kỳ..."/></label></div></section>
  <section className="print-form-section"><div className="print-section-heading"><b>03</b><div><h2>Hình ảnh tham khảo</h2><p>Tải tối đa 10 ảnh JPG, PNG hoặc WebP.</p></div></div><label className={`print-image-drop${dragging?' is-dragging':''}`} onDragOver={e=>e.preventDefault()} onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop}><input type="file" accept="image/*" multiple hidden onChange={select}/><strong>Thả hình ảnh vào đây</strong><span>hoặc nhấn để chọn ảnh từ thiết bị</span></label>{files.length?<div className="print-preview-grid">{files.map((file,index)=><article key={`${file.name}-${index}`}><img src={URL.createObjectURL(file)} alt=""/><span>{file.name}</span><button type="button" onClick={()=>setFiles(current=>current.filter((_,i)=>i!==index))}>×</button></article>)}</div>:null}</section>
  <div className="print-submit"><div><strong>Shop sẽ kiểm tra trước khi báo giá</strong><span>Gửi yêu cầu không phát sinh thanh toán.</span></div><button type="submit" disabled={submitting}>{submitting?'Đang gửi...':'Gửi yêu cầu in'}</button></div>{message?<p className="print-form-message" role="status">{message}</p>:null}
 </form>
}
